In [1]:
import functions
import os
import random
import shutil
import numpy as np
from PIL import Image
import timeit
import itertools
#import cv2

First we import the data into a dictionary that contains all the grayscale values of our images

In [2]:
all_data = functions.get_all_data()

In [5]:
test = all_data['1'][9]
print(test.shape)
print(test)

img = Image.fromarray(test, "L" )
img.save("test.png")

(45, 46)
[[255 255 255 ... 254 255 255]
 [255 255 255 ... 255 252 255]
 [255 255 255 ... 252 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [9]:
print(functions.getList(all_data)) 

dict_keys(['div', 'times', 'sin', '9', '0', '7', '+', '6', '1', '8', 'cos', '-', 'sqrt', 'pi', 'log', 'theta', '!', '(', '=', '4', '3', ')', '2', '5'])


In [10]:
numsKeys = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
oprKeys = ["+", "-", "div", "times"]
filterByKey = lambda keys: {x: all_data[x] for x in keys}
nums = filterByKey(numsKeys)
opr = filterByKey(oprKeys)

In [12]:
################## Using nested fors

start = timeit.default_timer()
root = os.getcwd()
for num1 in nums:
    for opr1 in opr:
        for num2 in nums:
            path = ""+ root + "/generated_images/" + num1 + opr1 + num2
            
            #Check if the directory already exists
            if os.path.exists(path):    
                #print ("Directory %s replaced" % path)
                shutil.rmtree(path)
            os.makedirs(path)
            
            #create a series of random images for training
            for i in range(10):    
                eqn = np.concatenate((random.choice(nums[num1]), random.choice(opr[opr1]), random.choice(nums[num2])), axis=1)
                img = Image.fromarray(eqn , 'L')
                img.save(path+"/"+str(i)+".png")
stop = timeit.default_timer()
print('Time: '+ str(stop-start))

#8.14 sec 1st method


Time: 7.905387873000109


In [ ]:
################## Using itertools

start = timeit.default_timer()
root = os.getcwd()
for element in itertools.product(nums,opr,nums):
    path = ""+ root + "/generated_images/" + str(element[0]+element[1]+element[2])
    #Check if the directory already exists
    if os.path.exists(path):    
        #print ("Directory %s replaced" % path)
        shutil.rmtree(path)
    os.makedirs(path)
    #create a series of random images for training
    for i in range(10):    
        eqn = np.concatenate((random.choice(nums[element[0]]), random.choice(opr[element[1]]), random.choice(nums[element[2]])), axis=1)
        img = Image.fromarray(eqn , 'L')
        img.save(path+"/"+str(i)+".png")
stop = timeit.default_timer()
print('Time: '+ str(stop-start))

#9.85 sec 2nd method
