In [1]:
import functions
import os
import random
import shutil
import numpy as np
from PIL import Image
import timeit
import itertools
#import cv2

First we import the data into a dictionary that contains all the grayscale values of our images

In [5]:
numbers_library = functions.get_all_data('images_no_copies')

Test


In [9]:
test = numbers_library['1'][7]
print(test.shape)
print(test)

img = Image.fromarray(test, "L" )
img.save("test.png")

(45, 46)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [7]:
print(functions.getList(numbers_library)) 

dict_keys(['div', 'times', 'sin', '9', '0', '7', '+', '6', '1', '8', 'cos', '-', 'sqrt', 'pi', 'log', 'theta', '!', '(', '=', '4', '3', ')', '2', '5'])


In [8]:
numsKeys = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
oprKeys = ["+", "-", "div", "times"]
filterByKey = lambda keys: {x: numbers_library[x] for x in keys}
nums = filterByKey(numsKeys)
opr = filterByKey(oprKeys)

In [12]:
################## Using nested fors

start = timeit.default_timer()
root = os.getcwd()
for num1 in nums:
    for opr1 in opr:
        for num2 in nums:
            path = ""+ root + "/generated_images/" + num1 + opr1 + num2
            
            #Check if the directory already exists
            if os.path.exists(path):    
                #print ("Directory %s replaced" % path)
                shutil.rmtree(path)
            os.makedirs(path)
            
            #create a series of random images for training
            for i in range(10):    
                eqn = np.concatenate((random.choice(nums[num1]), random.choice(opr[opr1]), random.choice(nums[num2])), axis=1)
                img = Image.fromarray(eqn , 'L')
                img.save(path+"/"+str(i)+".png")
stop = timeit.default_timer()
print('Time: '+ str(stop-start))

#8.14 sec 1st method


Time: 7.905387873000109


In [14]:
################## Using itertools
start = timeit.default_timer()
root = os.getcwd()
for element in itertools.product(nums,opr,nums):
    path = ""+ root + "/generated_images/" + str(element[0]+element[1]+element[2])
    #Check if the directory already exists
    if os.path.exists(path):    
        #print ("Directory %s replaced" % path)
        shutil.rmtree(path)
    os.makedirs(path)
    #create a series of random images for training
    for i in range(10):    
        eqn = np.concatenate((random.choice(nums[element[0]]), random.choice(opr[element[1]]), random.choice(nums[element[2]])), axis=1)
        img = Image.fromarray(eqn , 'L')
        img.save(path+"/"+str(i)+".png")
stop = timeit.default_timer()
print('Time: '+ str(stop-start))

#9.85 sec 2nd method


Time: 3.6109992940000666


In [14]:
############## Get all the current images into the library
numbers_library.update(functions.get_all_data('generated_images'))

Test


In [19]:
test2 = numbers_library['0times0'][3]
print(test2.shape)
print(test2)

img2 = Image.fromarray(test2, "L" )
img2.save("x.png")

(45, 139)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 254 253 ... 255 255 255]
 [254 255 255 ... 255 255 255]
 [255 251 255 ... 255 255 255]]


In [24]:
print('All the different symbols and equations are: \n\n'+ str(functions.getList(numbers_library)) )

All the different symbols and equations are: 

dict_keys(['div', 'times', 'sin', '9', '0', '7', '+', '6', '1', '8', 'cos', '-', 'sqrt', 'pi', 'log', 'theta', '!', '(', '=', '4', '3', ')', '2', '5', '5times5', '1div7', '1div0', '5times2', '2div8', '2div1', '1div9', '2div6', '7times3', '3div6', '0div9', '3div1', '7times4', '3div8', '0div0', '0div7', '2div7', '2div0', '1div8', '5times3', '1div1', '2div9', '1div6', '5times4', '0div6', '3div9', '0div1', '0div8', '3div0', '7times5', '7times2', '3div7', '7div7', '8times6', '5-7', '1+3', '9+0', '1+4', '8times1', '5-0', '7div0', '4div8', '3+9', '9+7', '7-4', '4div1', '3times2', '3+0', '8times8', '5-9', '7div9', '3+7', '9+9', '4div6', '3times5', '7-3', '7+8', '9-2', '5div6', '1-1', '5+5', '9-5', '6div9', '5+2', '1-6', '5div1', '5div8', '3-2', '6div0', '7+6', '1times4', '1-8', '1times3', '7+1', '6div7', '3-5', '9+8', '3+6', '7-2', '4div7', '3times4', '4div0', '3times3', '7-5', '3+1', '7div8', '8times9', '5-8', '7div1', '1+5', '8times0', '5-1', '4