In [103]:
from PIL import Image
import numpy as np

In [104]:
im = Image.open('./EXAMPLE/2_L/2_L_2.jpg') # Can be many different formats.
pix = im.load()

im.size

(60, 80)

In [105]:
arr = np.array(im)
arr[26,20]

40

In [106]:
arr[0,0]

180

In [107]:
arr[20,26]

179

In [108]:
arr2 = arr.transpose()
arr2[25,:]

array([180, 180, 180, 180, 180, 180, 180, 180, 170, 186, 164, 194,  35,
        36,  17, 184, 185, 176, 185, 178, 178, 186, 177, 184, 185, 174,
       169, 193, 170, 195, 165, 181, 184, 171, 174, 194, 154,  81,  52,
        44,  39,  68,  50,  95, 165, 188, 199, 176, 180, 180, 180, 180,
       180, 180, 180, 180, 185, 171, 181, 187, 173,  78,  33,  58, 180,
       180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180,
       180, 180], dtype=uint8)

In [109]:
arr2[arr2<=175] = 1
arr2[arr2>175] = 0

arr2[26,:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [100]:
arr2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [97]:
im.show()