In [8]:
import functions
import os
import random
import shutil
import numpy as np
from PIL import Image
import timeit
import itertools
#import cv2

First we import the data into a dictionary that contains all the grayscale values of our images

In [9]:
numbers_library = functions.get_array_from_images('../images_no_copies')

Test


In [5]:
test = numbers_library['1'][7]
print(test.shape)
print(test)

img = Image.fromarray(test, "L" )
img.save("test.png")

(45, 46)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [6]:
print(functions.getList(numbers_library)) 

dict_keys(['div', 'times', '9', '0', '7', '+', '6', '1', '8', '-', '4', '3', '2', '5'])


In [21]:
numsKeys = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
oprKeys = ["+", "-", "div", "times"]
filterByKey = lambda keys: {x: numbers_library[x] for x in keys}
nums = filterByKey(numsKeys)
opr = filterByKey(oprKeys)

In [22]:
################## Using nested fors

start = timeit.default_timer()
root = os.getcwd()
for num1 in nums:
    for opr1 in opr:
        for num2 in nums:
            path = ""+ root + "/../generated_images/" + num1 + opr1 + num2
            
            #Check if the directory already exists
            if os.path.exists(path):    
                #print ("Directory %s replaced" % path)
                shutil.rmtree(path)
            os.makedirs(path)
            
            #create a series of random images for training
            for i in range(10):    
                eqn = np.concatenate((random.choice(nums[num1]), random.choice(opr[opr1]), random.choice(nums[num2])), axis=1)
                img = Image.fromarray(eqn , 'L')
                img.save(path+"/"+str(i)+".png")
stop = timeit.default_timer()
print('Time: '+ str(stop-start))

#8.14 sec 1st method


Time: 3.642081699000016


In [9]:
################## Using itertools
start = timeit.default_timer()
root = os.getcwd()
for element in itertools.product(nums,opr,nums):
    path = ""+ root + "..//generated_images/" + str(element[0]+element[1]+element[2])
    #Check if the directory already exists
    if os.path.exists(path):    
        #print ("Directory %s replaced" % path)
        shutil.rmtree(path)
    os.makedirs(path)
    #create a series of random images for training
    for i in range(10):    
        eqn = np.concatenate((random.choice(nums[element[0]]), random.choice(opr[element[1]]), random.choice(nums[element[2]])), axis=1)
        img = Image.fromarray(eqn , 'L')
        img.save(path+"/"+str(i)+".png")
stop = timeit.default_timer()
print('Time: '+ str(stop-start))

#9.85 sec 2nd method


Time: 2.40400694199991


In [11]:
############## Get all the current images into the library
numbers_library.update(functions.get_array_from_images('../generated_images'))

Test


In [7]:
test2 = numbers_library['0times0'][6]
print(test2.shape)
print(test2)

img2 = Image.fromarray(test2, "L" )
img2.save("x.png")

KeyError: '0times0'

In [6]:
print('All the different symbols and equations are: \n\n'+ str(functions.getList(numbers_library)) )

All the different symbols and equations are: 

dict_keys(['div', 'times', '9', '0', '7', '+', '6', '1', '8', '-', '4', '3', '2', '5'])


In [18]:
import pandas as pd

In [8]:
######### Save into a .csv file of 2D entries
(pd.DataFrame.from_dict(data=numbers_library, orient='index')
   .to_csv('dict_file.csv', header=False))

In [8]:
import csv

In [30]:
colNames = ["pixel" + str(i+1) for i in range(len(numbers_library['1'][1].flatten()))]
colNames.insert(0,'Symbol')

In [32]:
#make new csv file
with open('good.csv','w') as fd:
    writer = csv.writer(fd)
    writer.writerow(colNames)

# Add all the arrays into the csv
for symbols in numbers_library:
    #for arrays in range(symbols):
    for array in range(len(numbers_library[symbols])):
        a = np.array(numbers_library[symbols][array])
        a = list(a.flatten())
        a.insert(0,symbols)
        #print("Symbol " + str(symbols) + ":    \t" + str(a))
        with open('good.csv','a') as fd:
            writer = csv.writer(fd)
            writer.writerow(a)

In [33]:
df = pd.read_csv('good.csv')
print(df)

Symbol  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0        div     255     255     255     255     255     255     255     255   
1        div     255     255     255     255     255     255     255     255   
2        div     255     255     255     255     255     255     255     255   
3        div     255     255     255     255     255     255     255     255   
4        div     255     255     255     255     255     255     255     255   
5        div     255     255     255     255     255     255     255     255   
6        div     255     255     255     255     255     255     255     255   
7        div     255     255     255     255     255     255     255     255   
8        div     255     255     255     255     255     255     255     255   
9        div     255     255     255     255     255     255     255     255   
10       div     255     255     255     255     255     255     255     255   
11       div     255     255     255     255  