In [2]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt


In [3]:
im = Image.open('.././images_no_copies/1/1_113653.jpg') # Can be many different formats.
pix = im.load()

im.size

(45, 45)

In [3]:
arr = np.array(im)
arr[26,20]

255

In [4]:
arr[0,0]

255

In [5]:
arr[1,:]


array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 253,
       255, 255,   0,   5, 253, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255], dtype=uint8)

In [6]:
arr

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [7]:
arr[:,27]

array([254, 255,   0,   0, 255, 252, 255, 255, 255, 255, 251, 255, 253,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 254, 255, 254, 255, 255, 255,   0,   2,   1,   3,   0,
         0,   0,   0,   0,   0,   0], dtype=uint8)

In [8]:
arr2 = arr.transpose()
arr2[27,:]

array([254, 255,   0,   0, 255, 252, 255, 255, 255, 255, 251, 255, 253,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 254, 255, 254, 255, 255, 255,   0,   2,   1,   3,   0,
         0,   0,   0,   0,   0,   0], dtype=uint8)

In [9]:
arr2[arr2<250] = 1 #make all the pained areas a 1 and the white areas a 0
arr2[arr2>=250] = 0

In [10]:
arr2[27,:]

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1], dtype=uint8)

In [11]:
arr2


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
import functions

In [5]:
labels = functions.get_array_from_images('../images_no_copies')

Test


In [6]:
num1 = labels['5'][1]
num2 = labels['3'][1]
opr1 = labels['-'][1]


In [7]:
img = Image.fromarray(num1 , 'L')
img.show()
img = Image.fromarray(num2 , 'L')
img.show()

In [8]:
eqn = np.concatenate((num1, opr1, num2), axis=1)
img = Image.fromarray(eqn , 'L')
img.show()
eqn


array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)